# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 666bdeafb78393b3981f9d048ce59e6af0030cb0dc749b229817fbf3bfd285fa825d71f81b2fd103c3c1365301045267e88107905389e6c91933e3eed71db23a

test:
  secret_key_base: d0c7e2d9eddef756cd615a8f5c6781f25cd52cee6eba12755199a5bd83084f614b75d465d3d3fc9b7cf98be5376bb695c7796b7c298145dffe80d01ba35d30c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
